"""更改token表

Revision ID: 2948163b2c38
Revises: 8a5b470931d5
Create Date: 2026-07-16 02:30:55.437309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2948163b2c38'
down_revision: Union[str, Sequence[str], None] = '8a5b470931d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_tokens', sa.Column('email', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_tokens', 'email')
    # ### end Alembic commands ###
