"""add organization

Revision ID: 2dea894bdc13
Revises: 9ba4193316b1
Create Date: 2026-07-21 18:11:43.187250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dea894bdc13'
down_revision: Union[str, Sequence[str], None] = '9ba4193316b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='组织ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='组织描述'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
