"""更改token位置

Revision ID: 507768dce550
Revises: 1e095cea29cd
Create Date: 2026-07-16 02:14:30.383046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '507768dce550'
down_revision: Union[str, Sequence[str], None] = '1e095cea29cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=True),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['users_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users_request', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_request', sa.Column('token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
