"""更改token表

Revision ID: 8a5b470931d5
Revises: 507768dce550
Create Date: 2026-07-16 02:16:55.835161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a5b470931d5'
down_revision: Union[str, Sequence[str], None] = '507768dce550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_request', 'created_at')
    op.drop_column('users_request', 'expire_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_request', sa.Column('expire_at', mysql.TIMESTAMP(), nullable=True))
    op.add_column('users_request', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False))
    # ### end Alembic commands ###
