"""添加知识库表

Revision ID: 8c9f12c0360c
Revises: 8dfeb1032d81
Create Date: 2026-07-21 22:14:12.043357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9f12c0360c'
down_revision: Union[str, Sequence[str], None] = '8dfeb1032d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='知识库唯一ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='可见范围: public-公开, org-组织内, personal-个人'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建者用户ID'),
    sa.Column('org_id', sa.BigInteger(), nullable=True, comment='所属组织ID, 个人知识库为空'),
    sa.Column('embedding_model', sa.String(length=100), nullable=True, comment='向量化模型名称, 如 text-embedding-3-small'),
    sa.Column('vector_store', sa.String(length=100), nullable=True, comment='向量存储类型, 如 chroma/pgvector'),
    sa.Column('document_count', sa.Integer(), nullable=True, comment='文档总数统计'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='分块总数统计'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: building-构建中, ready-就绪, failed-构建失败'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='软删除标记: 0-未删除, 1-已删除'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库主表'
    )
    op.create_index('idx_org', 'knowledge_base', ['org_id'], unique=False)
    op.create_index('idx_owner', 'knowledge_base', ['owner_id'], unique=False)
    op.create_index('idx_scope', 'knowledge_base', ['scope'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='文档ID'),
    sa.Column('kb_id', sa.BigInteger(), nullable=False, comment='所属知识库'),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False, comment='上传用户'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文档标题'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='pdf/docx/md/txt/html'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='application/pdf'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(Byte)'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='服务器存储路径'),
    sa.Column('parser_status', sa.String(length=20), nullable=True, comment='waiting/parsing/embedding/completed/failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='切块数量'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='失败原因或备注'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档表'
    )
    op.create_index('idx_kb', 'document', ['kb_id'], unique=False)
    op.create_index('idx_status', 'document', ['parser_status'], unique=False)
    op.create_index('idx_uploader', 'document', ['uploader_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='分块唯一ID'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='所属文档ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=True, comment='分块序号(从0开始)'),
    sa.Column('content', sa.Text(), nullable=True, comment='分块文本内容'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Token数量估算'),
    sa.Column('vector_id', sa.String(length=255), nullable=True, comment='向量数据库中的向量ID'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='文档分块表'
    )
    op.create_index('idx_document', 'chunk', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index('idx_uploader', table_name='document')
    op.drop_index('idx_status', table_name='document')
    op.drop_index('idx_kb', table_name='document')
    op.drop_table('document')
    op.drop_index('idx_scope', table_name='knowledge_base')
    op.drop_index('idx_owner', table_name='knowledge_base')
    op.drop_index('idx_org', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
