"""添加知识库表

Revision ID: 8dfeb1032d81
Revises: 2dea894bdc13
Create Date: 2026-07-21 22:10:57.638470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8dfeb1032d81'
down_revision: Union[str, Sequence[str], None] = '2dea894bdc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_member', 'id',
               existing_type=mysql.BIGINT(),
               comment='成员ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_member', 'org_id',
               existing_type=mysql.BIGINT(),
               comment='组织ID',
               existing_nullable=False)
    op.alter_column('organization_member', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('organization_member', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
               comment='角色: owner/admin/member',
               existing_comment='owner admin member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.alter_column('organization_member', 'joined_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               comment='加入时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_member', 'joined_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               comment=None,
               existing_comment='加入时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organization_member', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
               type_=mysql.VARCHAR(length=20),
               comment='owner admin member',
               existing_comment='角色: owner/admin/member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'"))
    op.alter_column('organization_member', 'user_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('organization_member', 'org_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='组织ID',
               existing_nullable=False)
    op.alter_column('organization_member', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='成员ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
