"""fix user

Revision ID: 9ba4193316b1
Revises: 391688f78d89
Create Date: 2026-07-21 18:10:10.867623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ba4193316b1'
down_revision: Union[str, Sequence[str], None] = '391688f78d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_table('organization')
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('organization',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='组织ID'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='组织名称'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='组织描述'),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True, comment='头像'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_org_owner')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    # ### end Alembic commands ###
