"""init

Revision ID: a83d054ff604
Revises: 
Create Date: 2026-09-01 01:38:46.045372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83d054ff604'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=True),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['users_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='组织ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='组织描述'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='软删除标记'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='知识库唯一ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识库描述'),
    sa.Column('scope', sa.Enum('PUBLIC', 'ORG', 'PERSONAL', name='knowledgesource'), nullable=False, comment='可见范围: public-公开, org-组织内, personal-个人'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建者用户ID'),
    sa.Column('org_id', sa.BigInteger(), nullable=True, comment='所属组织ID, 个人知识库为空'),
    sa.Column('document_count', sa.Integer(), nullable=True, comment='文档总数统计'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='分块总数统计'),
    sa.Column('chunk_size', sa.Integer(), nullable=True, comment='分块大小'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True, comment='分块重叠长度'),
    sa.Column('status', sa.Enum('ACTIVE', 'PROVISIONING', 'ARCHIVED', 'FAILED', name='kbstatus'), nullable=True, comment='状态:active:正常使用,processing:正在初始化,archived:归档,failed:异常'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='软删除标记: 0-未删除, 1-已删除'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库主表'
    )
    op.create_index('idx_org', 'knowledge_base', ['org_id'], unique=False)
    op.create_index('idx_owner', 'knowledge_base', ['owner_id'], unique=False)
    op.create_index('idx_scope', 'knowledge_base', ['scope'], unique=False)
    op.create_table('organization_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='成员ID'),
    sa.Column('org_id', sa.BigInteger(), nullable=False, comment='组织ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'), nullable=False, comment='角色: owner/admin/member'),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='加入时间'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uk_org_user')
    )
    op.create_index('idx_user', 'organization_member', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='文档ID'),
    sa.Column('kb_id', sa.BigInteger(), nullable=False, comment='所属知识库'),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False, comment='上传用户'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文档标题'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='pdf/docx/md/txt/html'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='application/pdf'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(Byte)'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件Hash'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='文档页数'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='服务器存储路径'),
    sa.Column('parser_status', sa.Enum('WAITING', 'PARSING', 'EMBEDDING', 'COMPLETED', 'FAILED', name='parserstatus'), nullable=True, comment='waiting/parsing/embedding/completed/failed'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='切块数量'),
    sa.Column('parse_duration', sa.Integer(), nullable=True, comment='解析耗时(秒)'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='失败原因或备注'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文档表'
    )
    op.create_index('idx_kb', 'document', ['kb_id'], unique=False)
    op.create_index('idx_status', 'document', ['parser_status'], unique=False)
    op.create_index('idx_uploader', 'document', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_document_file_hash'), 'document', ['file_hash'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='分块唯一ID'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='所属文档ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=True, comment='分块序号(从0开始)'),
    sa.Column('content', sa.Text(), nullable=True, comment='分块文本内容'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Token数量估算'),
    sa.Column('vector_id', sa.String(length=255), nullable=True, comment='向量数据库中的向量ID'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='文档分块表'
    )
    op.create_index('idx_document', 'chunk', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_file_hash'), table_name='document')
    op.drop_index('idx_uploader', table_name='document')
    op.drop_index('idx_status', table_name='document')
    op.drop_index('idx_kb', table_name='document')
    op.drop_table('document')
    op.drop_index('idx_user', table_name='organization_member')
    op.drop_table('organization_member')
    op.drop_index('idx_scope', table_name='knowledge_base')
    op.drop_index('idx_owner', table_name='knowledge_base')
    op.drop_index('idx_org', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('invite_tokens')
    op.drop_table('users_request')
    op.drop_table('users')
    # ### end Alembic commands ###
