"""更新request表

Revision ID: b3336696fde1
Revises: 2948163b2c38
Create Date: 2026-07-17 00:32:46.192398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3336696fde1'
down_revision: Union[str, Sequence[str], None] = '2948163b2c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_request', 'approved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_request', sa.Column('approved_at', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
